/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fc211026_specialLabsheet;

import java.awt.Color;

/**
 *
 * @author menur
 */
public class InsertData extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public InsertData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subject01ButtonGroup = new javax.swing.ButtonGroup();
        buject02ButtonGroup = new javax.swing.ButtonGroup();
        subject03ButtonGroup = new javax.swing.ButtonGroup();
        gobackButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        indexNumLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        subject01Label = new javax.swing.JLabel();
        subject02Label = new javax.swing.JLabel();
        subject03Label = new javax.swing.JLabel();
        currentGPALabel = new javax.swing.JLabel();
        indexNumErrorMassegeLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        indexNumTextField = new javax.swing.JTextField(20);
        indexNumTextField = new javax.swing.JTextField();
        fullNameTextField = new javax.swing.JTextField();
        currentGPATextField = new javax.swing.JTextField();
        mathematicsRadioButton = new javax.swing.JRadioButton();
        bilogyRadioButton = new javax.swing.JRadioButton();
        bilogyRadioButton1 = new javax.swing.JRadioButton();
        bilogyRadioButton2 = new javax.swing.JRadioButton();
        statisticsRadioButton = new javax.swing.JRadioButton();
        chemistryRadioButton = new javax.swing.JRadioButton();
        physicsRadioButton = new javax.swing.JRadioButton();
        ictRadioButton1 = new javax.swing.JRadioButton();
        eesRadioButton1 = new javax.swing.JRadioButton();
        dbmsRadioButton = new javax.swing.JRadioButton();
        subject03ErrorMassegeLabel = new javax.swing.JLabel();
        subject02ErrorMassegeLabel = new javax.swing.JLabel();
        subject01ErrorMassegeLabel = new javax.swing.JLabel();
        operationMassegeLabel = new javax.swing.JLabel();
        insertButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gobackButton.setBackground(new java.awt.Color(255, 255, 255));
        gobackButton.setForeground(new java.awt.Color(0, 0, 0));
        gobackButton.setText("GO BACK");
        gobackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gobackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        titleLabel.setBackground(new java.awt.Color(0, 102, 102));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("INSERT STUDENT DATA");
        titleLabel.setOpaque(true);
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 40));

        indexNumLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        indexNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        indexNumLabel.setText("INDEX NUMBER ");
        getContentPane().add(indexNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        fullNameLabel.setText("FULL NAME");
        getContentPane().add(fullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        subject01Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subject01Label.setForeground(new java.awt.Color(255, 255, 255));
        subject01Label.setText("SUBJECT 01");
        getContentPane().add(subject01Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 30));

        subject02Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subject02Label.setForeground(new java.awt.Color(255, 255, 255));
        subject02Label.setText("SUBJECT 02");
        getContentPane().add(subject02Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, 30));

        subject03Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subject03Label.setForeground(new java.awt.Color(255, 255, 255));
        subject03Label.setText("SUBJECT 03");
        getContentPane().add(subject03Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 30));

        currentGPALabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentGPALabel.setForeground(new java.awt.Color(255, 255, 255));
        currentGPALabel.setText("CURRENT GPA");
        getContentPane().add(currentGPALabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 30));

        indexNumErrorMassegeLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(indexNumErrorMassegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 430, 30));

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        indexNumTextField.setBackground(new java.awt.Color(204, 204, 204));
        indexNumTextField.setForeground(new java.awt.Color(0, 0, 0));
        indexNumTextField.setText("fc######");
        indexNumTextField.setToolTipText("");
        indexNumTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        indexNumTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        indexNumTextField.setDoubleBuffered(true);
        indexNumTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                indexNumTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                indexNumTextFieldFocusLost(evt);
            }
        });
        getContentPane().add(indexNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 30));

        fullNameTextField.setBackground(new java.awt.Color(204, 204, 204));
        fullNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        fullNameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        fullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fullNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 550, 30));

        currentGPATextField.setBackground(new java.awt.Color(204, 204, 204));
        currentGPATextField.setForeground(new java.awt.Color(0, 0, 0));
        currentGPATextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 4, 1, 1));
        getContentPane().add(currentGPATextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 110, 30));

        subject01ButtonGroup.add(mathematicsRadioButton);
        mathematicsRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        mathematicsRadioButton.setText("MATHEMATICS ");
        mathematicsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathematicsRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mathematicsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        subject01ButtonGroup.add(bilogyRadioButton);
        bilogyRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        bilogyRadioButton.setText("PLANT BIOLOGY");
        bilogyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilogyRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bilogyRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 30));

        subject01ButtonGroup.add(bilogyRadioButton1);
        bilogyRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        bilogyRadioButton1.setText("ZOOLOGY");
        bilogyRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilogyRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(bilogyRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, 30));

        subject01ButtonGroup.add(bilogyRadioButton2);
        bilogyRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        bilogyRadioButton2.setText("MICROBIOLOGY");
        bilogyRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilogyRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(bilogyRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 30));

        buject02ButtonGroup.add(statisticsRadioButton);
        statisticsRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        statisticsRadioButton.setText("STATISTICS");
        statisticsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(statisticsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 30));

        buject02ButtonGroup.add(chemistryRadioButton);
        chemistryRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        chemistryRadioButton.setText("CHEMISTRY");
        chemistryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chemistryRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 30));

        buject02ButtonGroup.add(physicsRadioButton);
        physicsRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        physicsRadioButton.setText("PHYSICS");
        physicsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(physicsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, 30));

        subject03ButtonGroup.add(ictRadioButton1);
        ictRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        ictRadioButton1.setText("ICT");
        ictRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ictRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ictRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        subject03ButtonGroup.add(eesRadioButton1);
        eesRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        eesRadioButton1.setText("EES");
        eesRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eesRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(eesRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));

        subject03ButtonGroup.add(dbmsRadioButton);
        dbmsRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        dbmsRadioButton.setText("DBMS");
        dbmsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbmsRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dbmsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, 30));

        subject03ErrorMassegeLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(subject03ErrorMassegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 30));

        subject02ErrorMassegeLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(subject02ErrorMassegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 130, 30));

        subject01ErrorMassegeLabel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(subject01ErrorMassegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 156, 90, 20));

        operationMassegeLabel.setForeground(new java.awt.Color(51, 255, 255));
        operationMassegeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(operationMassegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 230, 20));

        insertButton.setBackground(new java.awt.Color(204, 255, 255));
        insertButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insertButton.setForeground(new java.awt.Color(0, 0, 0));
        insertButton.setText("INSERT");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(insertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 140, 50));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fc211026_specialLabsheet/menuBackground1.jpg"))); // NOI18N
        backgroundLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void gobackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackButtonActionPerformed
        setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_gobackButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        getInput();
        operationMassegeLabel.setText("");
        indexNumErrorMassegeLabel.setText("");
        subject01ErrorMassegeLabel.setText("");
        subject02ErrorMassegeLabel.setText("");
        subject02ErrorMassegeLabel.setText("");
        if(checkIndexValidity() && checkSubjectValidity() ){
            if(DatabaseOperations.insertData(inputData[0], inputData[1],inputData[2], inputData[3], inputData[4], inputData[5])){
                operationMassegeLabel.setText("- Insertion Success -");
            }else{
                operationMassegeLabel.setText("- Insertion NOT Success -");
                indexNumErrorMassegeLabel.setText("Index Number is already exsists");
            }
        }else {
            operationMassegeLabel.setText("- Insertion NOT Success -");
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void mathematicsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathematicsRadioButtonActionPerformed
        subject01="Mathematics";
    }//GEN-LAST:event_mathematicsRadioButtonActionPerformed

    private void bilogyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilogyRadioButtonActionPerformed
        subject01="Plant Biology";
    }//GEN-LAST:event_bilogyRadioButtonActionPerformed

    private void bilogyRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilogyRadioButton2ActionPerformed
        subject01="Microbiology";
    }//GEN-LAST:event_bilogyRadioButton2ActionPerformed

    private void bilogyRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilogyRadioButton1ActionPerformed
        subject01="Zoology";
    }//GEN-LAST:event_bilogyRadioButton1ActionPerformed

    private void chemistryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryRadioButtonActionPerformed
        subject02="Chemistry";
    }//GEN-LAST:event_chemistryRadioButtonActionPerformed

    private void statisticsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsRadioButtonActionPerformed
        subject02="Statistics";
    }//GEN-LAST:event_statisticsRadioButtonActionPerformed

    private void physicsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsRadioButtonActionPerformed
        subject02="Physics";
    }//GEN-LAST:event_physicsRadioButtonActionPerformed

    private void ictRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ictRadioButton1ActionPerformed
        subject03="ICT";
    }//GEN-LAST:event_ictRadioButton1ActionPerformed

    private void eesRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eesRadioButton1ActionPerformed
        subject03="EES";
    }//GEN-LAST:event_eesRadioButton1ActionPerformed

    private void dbmsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbmsRadioButtonActionPerformed
        subject03="DBMS";
    }//GEN-LAST:event_dbmsRadioButtonActionPerformed

    private void fullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextFieldActionPerformed

    private void indexNumTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indexNumTextFieldFocusGained
        if(indexNumTextField.getText().equals("fc######")){
           indexNumTextField.setText("");
           indexNumTextField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_indexNumTextFieldFocusGained

    private void indexNumTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indexNumTextFieldFocusLost
        if(indexNumTextField.getText().equals("")){
           indexNumTextField.setText("fc######");
           indexNumTextField.setForeground(new Color(140,140,140));
        }
    }//GEN-LAST:event_indexNumTextFieldFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    
    private void getInput(){
        inputData[0]=indexNumTextField.getText();
        inputData[1]=fullNameTextField.getText();
        inputData[2]=subject01;
        inputData[3]=subject02;
        inputData[4]=subject03;
        inputData[5]=currentGPATextField.getText();
    }
    
    private boolean checkIndexValidity(){
        char[] indexChar=inputData[0].toCharArray();
        if(indexChar[0]!='f' || indexChar[1]!='c' || indexChar.length!=8){
            indexNumErrorMassegeLabel.setText("NOT in correct format.");
            return false;
        }else{
            for(int i=2; i<8; i++){
                if(!Character.isDigit(indexChar[i])){
                    indexNumErrorMassegeLabel.setText("Not in correct format.");
                    return false;
                }
            }
        }
        return true;
    }
    
    private boolean checkSubjectValidity(){
        if(subject01==null){
            subject01ErrorMassegeLabel.setText("Can't left empty");
            return false;    
        }else if(subject02==null){
            subject02ErrorMassegeLabel.setText("Can't left empty");
            return false;
        }else if(subject03==null){
            subject03ErrorMassegeLabel.setText("Can't left empty");
            return false;
        }else{
            return true;
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertData().setVisible(true);
            }
        });
    }

    
    private String[] inputData=new String[6];
    private String subject01=null;
    private String subject02=null;
    private String subject03=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JRadioButton bilogyRadioButton;
    private javax.swing.JRadioButton bilogyRadioButton1;
    private javax.swing.JRadioButton bilogyRadioButton2;
    private javax.swing.ButtonGroup buject02ButtonGroup;
    private javax.swing.JRadioButton chemistryRadioButton;
    private javax.swing.JLabel currentGPALabel;
    private javax.swing.JTextField currentGPATextField;
    private javax.swing.JRadioButton dbmsRadioButton;
    private javax.swing.JRadioButton eesRadioButton1;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JButton gobackButton;
    private javax.swing.JRadioButton ictRadioButton1;
    private javax.swing.JLabel indexNumErrorMassegeLabel;
    private javax.swing.JLabel indexNumLabel;
    private javax.swing.JTextField indexNumTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JRadioButton mathematicsRadioButton;
    private javax.swing.JLabel operationMassegeLabel;
    private javax.swing.JRadioButton physicsRadioButton;
    private javax.swing.JRadioButton statisticsRadioButton;
    private javax.swing.ButtonGroup subject01ButtonGroup;
    private javax.swing.JLabel subject01ErrorMassegeLabel;
    private javax.swing.JLabel subject01Label;
    private javax.swing.JLabel subject02ErrorMassegeLabel;
    private javax.swing.JLabel subject02Label;
    private javax.swing.ButtonGroup subject03ButtonGroup;
    private javax.swing.JLabel subject03ErrorMassegeLabel;
    private javax.swing.JLabel subject03Label;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
